---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= Novidades da API REST do Astra Control
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp atualiza periodicamente a API REST do Astra Control para oferecer novos recursos, melhorias e correções de bugs.



== 5 de agosto de 2021 (21,08)

Esta versão inclui a introdução de um novo modelo de implantação Astra e uma grande expansão da API REST.



=== Modelo de implantação do Astra Control Center

Além da oferta existente do Astra Control Service fornecida como serviço de nuvem pública, esta versão também inclui o modelo de implantação no local do Astra Control Center. Você pode instalar o Astra Control Center no seu local para gerenciar seu ambiente Kubernetes local. Os dois modelos de implantação do Astra Control compartilham a mesma API REST, com pequenas diferenças observadas conforme necessário na documentação.



=== Expansão dos tipos de recursos REST

O número de recursos acessíveis por meio da API REST Astra Control foi muito ampliado, com muitos dos novos recursos fornecendo a base para a oferta do Astra Control Center no local. Os novos recursos incluem: ASUP, direito, recurso, licença, configuração, assinatura, bucket, nuvem, cluster, cluster gerenciado, back-end de storage e classe de storage. Consulte link:../endpoints/resources.html["Recursos"] para obter mais informações.



=== Pontos de extremidade adicionais compatíveis com a implantação do Astra

Além dos recursos REST expandidos, há vários outros pontos de extremidade de API novos disponíveis para dar suporte à implantação do Astra Control.

Suporte ao OpenAPI:: Os endpoints OpenAPI fornecem acesso ao documento JSON OpenAPI atual e a outros recursos relacionados.
Suporte ao OpenMetrics:: Os endpoints OpenMetrics fornecem acesso às métricas da conta por meio do recurso OpenMetrics.




== 15 de abril de 2021 (21,04)

Esta versão inclui os seguintes novos recursos e aprimoramentos.



=== Introdução da API REST

A API REST do Astra Control está disponível para uso com a oferta do Astra Control Service. Ele foi criado com base em TECNOLOGIAS REST e nas melhores práticas atuais. A API fornece uma base para a automação das implantações do Astra e inclui os recursos e benefícios a seguir.

Recursos:: Existem quatorze tipos de recursos REST disponíveis.
Acesso ao token de API:: O acesso à API REST é fornecido por meio de um token de acesso à API que você pode gerar na interface de usuário da Web Astra. O token de API fornece acesso seguro à API.
Suporte para coleções:: Há um conjunto rico de parâmetros de consulta que podem ser usados para acessar as coleções de recursos. Algumas das operações suportadas incluem filtragem, classificação e paginação.

