---
sidebar: sidebar 
permalink: workflows/wf_restore_app_backup.html 
keywords:  
summary:  
---
= Restaure um aplicativo gerenciado a partir de um backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode restaurar um aplicativo gerenciado criando um novo aplicativo a partir de um backup.



=== 1. Selecione a aplicação gerida para restaurar

Execute o fluxo de trabalho link:wf_list_man_apps.html["Liste os aplicativos gerenciados"] e selecione a aplicação que deseja clonar. Vários dos valores de recursos são necessários para a chamada REST usada para clonar o aplicativo.



=== 2. Selecione a cópia de segurança a utilizar

Execute o fluxo de trabalho link:wf_list_backups.html["Liste os backups"] e selecione cópia de segurança que pretende utilizar.



=== 3. Restaure a aplicação

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| POST | /Conta//k8s/v1/managedApps 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| JSON | Corpo | Sim | Fornece os parâmetros para o aplicativo clonado. Veja o exemplo abaixo. 
|===


===== Exemplo de entrada JSON

[source, json]
----
{
  "type": "application/astra-managedApp",
  "version": "1.0",
  "name": "postgres1-postgresql-clone",
  "clusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "sourceClusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "namespace": "davidns-postgres-app",
  "backupID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb",
  "sourceAppID": "e591ee59-ea90-4a9f-8e6c-d2b6e8647096"
}
----


===== Curl exemplo: Clonar um aplicativo a partir de um backup

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps' --header 'Content-Type: application/astra-managedApp+json' --header '*/*' --header 'Authorization: Bearer <API_TOKEN>' --d @JSONinput
----